"""empty message

Revision ID: 029324ec0004
Revises: bce2801a8dcb
Create Date: 2024-10-18 17:55:18.387336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029324ec0004'
down_revision = 'bce2801a8dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appmodel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('model_name', sa.String(length=99), nullable=True, comment='模型名称'),
    sa.Column('model_id', sa.String(length=99), nullable=True, comment='模型ID'),
    sa.Column('enable', sa.Integer(), nullable=True, comment='启用'),
    sa.Column('access_level', sa.Integer(), nullable=True, comment='访问限制'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='最近更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appmodel')
    # ### end Alembic commands ###
