"""empty message

Revision ID: 0aa5cdd94925
Revises: ec361b5f03c0
Create Date: 2024-10-10 15:33:50.850915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa5cdd94925'
down_revision = 'ec361b5f03c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark1', sa.String(length=255), nullable=True, comment='备注'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.drop_column('remark1')

    # ### end Alembic commands ###
