"""empty message

Revision ID: 80d0eb337b8f
Revises: 
Create Date: 2024-10-29 10:48:51.213478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d0eb337b8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('knowledgeName', sa.String(length=255), nullable=True, comment='知识库名字'),
    sa.Column('knowledgeId', sa.String(length=255), nullable=True, comment='知识库ID'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('starttime', sa.String(length=255), nullable=True),
    sa.Column('endtime', sa.String(length=255), nullable=True),
    sa.Column('totaltime', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.Column('tips', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pay_method', sa.String(length=16), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('pay_type', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('power',
    sa.Column('id', sa.Integer(), nullable=False, comment='权限编号'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='权限名称'),
    sa.Column('type', sa.String(length=1), nullable=True, comment='权限类型'),
    sa.Column('code', sa.String(length=30), nullable=True, comment='权限标识'),
    sa.Column('url', sa.String(length=255), nullable=True, comment='权限路径'),
    sa.Column('open_type', sa.String(length=10), nullable=True, comment='打开方式'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父类编号'),
    sa.Column('icon', sa.String(length=128), nullable=True, comment='图标'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('enable', sa.Integer(), nullable=True, comment='是否开启'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='角色名称'),
    sa.Column('code', sa.String(length=255), nullable=True, comment='角色标识'),
    sa.Column('enable', sa.Integer(), nullable=True, comment='是否启用'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('details', sa.String(length=255), nullable=True, comment='详情'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=20), nullable=True, comment='用户名'),
    sa.Column('realname', sa.String(length=20), nullable=True, comment='真实名字'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('password_hash', sa.String(length=128), nullable=True, comment='哈希密码'),
    sa.Column('enable', sa.Integer(), nullable=True, comment='启用'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='最近更新时间'),
    sa.Column('balance', sa.Float(precision=2), nullable=True, comment='用户余额'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appmodel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('model_name', sa.String(length=99), nullable=True, comment='模型名称'),
    sa.Column('model_id', sa.String(length=99), nullable=True, comment='模型ID'),
    sa.Column('enable', sa.Integer(), nullable=True, comment='启用'),
    sa.Column('access_level_id', sa.Integer(), nullable=True, comment='访问限制'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='最近更新时间'),
    sa.ForeignKeyConstraint(['access_level_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='标识'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户编号'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色编号'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('appmodel')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('power')
    op.drop_table('payorder')
    op.drop_table('log')
    op.drop_table('knowledge')
    # ### end Alembic commands ###
