"""empty message

Revision ID: a17006dd867d
Revises: 8d230b9d3779
Create Date: 2024-10-17 15:42:31.884289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17006dd867d'
down_revision = '8d230b9d3779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('knowledgeName', sa.String(length=20), nullable=True, comment='知识库名字'),
    sa.Column('knowledgeId', sa.String(length=20), nullable=True, comment='知识库ID'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge')
    # ### end Alembic commands ###
