"""empty message

Revision ID: b444a83c3e48
Revises: c0dc7bfb059e
Create Date: 2024-10-17 16:24:37.874722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b444a83c3e48'
down_revision = 'c0dc7bfb059e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge', schema=None) as batch_op:
        batch_op.alter_column('knowledgeId',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_comment='知识库ID',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge', schema=None) as batch_op:
        batch_op.alter_column('knowledgeId',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=20),
               existing_comment='知识库ID',
               existing_nullable=True)

    # ### end Alembic commands ###
