"""empty message

Revision ID: c0dc7bfb059e
Revises: a17006dd867d
Create Date: 2024-10-17 16:19:33.073011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0dc7bfb059e'
down_revision = 'a17006dd867d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge', schema=None) as batch_op:
        batch_op.drop_column('uid')

    # ### end Alembic commands ###
