"""empty message

Revision ID: c1ac831d3586
Revises: e7263c63c6fa
Create Date: 2024-10-18 21:09:22.082450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1ac831d3586'
down_revision = 'e7263c63c6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_level_id', sa.Integer(), nullable=True, comment='访问限制'))
        batch_op.create_foreign_key(None, 'role', ['access_level_id'], ['id'])
        batch_op.drop_column('access_level')

    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('appmodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_level', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='访问限制'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('access_level_id')

    # ### end Alembic commands ###
